<?php
namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LaporanSeeder extends Seeder
{
    public function run(): void
    {
        // Create 10 reports all assigned to teknisi_id = 1
        // Use a variety of statuses allowed by the schema: ['pending','ditolak','diproses','selesai','dikerjakan']
        // Ensure sarana_id values are unique to avoid ROW_NUMBER() partition hiding records
        DB::table('t_laporan_kerusakan')->insert([
            [
                'user_id'           => 3,
                'role'              => 'mhs',
                'gedung_id'         => 1,
                'lantai_id'         => 5,
                'ruang_id'          => 6,
                'sarana_id'         => 30,
                'teknisi_id'        => 1,
                'laporan_judul'     => 'Proyektor mati total di RT03',
                'laporan_foto'      => 'laporan_files/proyektor_rusak.jpg',
                'tingkat_kerusakan' => 'tinggi',
                'tingkat_urgensi'   => 'tinggi',
                'dampak_kerusakan'  => 'besar',
                'status_laporan'    => 'selesai',
                'tanggal_diproses'  => Carbon::now()->subDays(10),
                'tanggal_selesai'   => Carbon::now()->subDays(7),
                'bobot'             => 0.85,
                'created_at'        => Carbon::now()->subDays(12),
                'updated_at'        => Carbon::now()->subDays(7),
            ],
            [
                'user_id'           => 4,
                'role'              => 'dosen',
                'gedung_id'         => 1,
                'lantai_id'         => 5,
                'ruang_id'          => 2,
                'sarana_id'         => 31,
                'teknisi_id'        => 1,
                'laporan_judul'     => 'Kursi patah di Ruang Teori 01',
                'laporan_foto'      => null,
                'tingkat_kerusakan' => 'sedang',
                'tingkat_urgensi'   => 'sedang',
                'dampak_kerusakan'  => 'sedang',
                'status_laporan'    => 'selesai',
                'tanggal_diproses'  => Carbon::now()->subDays(8),
                'tanggal_selesai'   => Carbon::now()->subDays(5),
                'bobot'             => 0.55,
                'created_at'        => Carbon::now()->subDays(9),
                'updated_at'        => Carbon::now()->subDays(5),
            ],
            [
                'user_id'           => 5,
                'role'              => 'tendik',
                'gedung_id'         => 1,
                'lantai_id'         => 6,
                'ruang_id'          => 22,
                'sarana_id'         => 32,
                'teknisi_id'        => 1,
                'laporan_judul'     => 'Pintu ruangan tidak bisa dikunci',
                'laporan_foto'      => null,
                'tingkat_kerusakan' => 'rendah',
                'tingkat_urgensi'   => 'sedang',
                'dampak_kerusakan'  => 'sedang',
                'status_laporan'    => 'dikerjakan',
                'tanggal_diproses'  => Carbon::now()->subDays(6),
                'tanggal_selesai'   => null,
                'bobot'             => 0.42,
                'created_at'        => Carbon::now()->subDays(7),
                'updated_at'        => Carbon::now()->subDays(4),
            ],
            [
                'user_id'           => 4,
                'role'              => 'dosen',
                'gedung_id'         => 1,
                'lantai_id'         => 5,
                'ruang_id'          => 3,
                'sarana_id'         => 33,
                'teknisi_id'        => 1,
                'laporan_judul'     => 'Lampu neon mati di Ruang RT02',
                'laporan_foto'      => 'laporan_files/lampu_mati.jpg',
                'tingkat_kerusakan' => 'tinggi',
                'tingkat_urgensi'   => 'tinggi',
                'dampak_kerusakan'  => 'besar',
                'status_laporan'    => 'diproses',
                'tanggal_diproses'  => Carbon::now()->subDay(),
                'tanggal_selesai'   => null,
                'bobot'             => 0.80,
                'created_at'        => Carbon::now()->subDays(2),
                'updated_at'        => Carbon::now()->subDay(),
            ],
            [
                'user_id'           => 3,
                'role'              => 'mhs',
                'gedung_id'         => 1,
                'lantai_id'         => 5,
                'ruang_id'          => 6,
                'sarana_id'         => 34,
                'teknisi_id'        => 1,
                'laporan_judul'     => 'Kabel proyektor putus',
                'laporan_foto'      => null,
                'tingkat_kerusakan' => 'sedang',
                'tingkat_urgensi'   => 'tinggi',
                'dampak_kerusakan'  => 'sedang',
                'status_laporan'    => 'diproses',
                'tanggal_diproses'  => Carbon::now()->subHours(6),
                'tanggal_selesai'   => null,
                'bobot'             => 0.68,
                'created_at'        => Carbon::now()->subHours(18),
                'updated_at'        => Carbon::now()->subHours(6),
            ],
            [
                'user_id'           => 4,
                'role'              => 'dosen',
                'gedung_id'         => 1,
                'lantai_id'         => 6,
                'ruang_id'          => 22,
                'sarana_id'         => 35,
                'teknisi_id'        => 1,
                'laporan_judul'     => 'Lemari tidak bisa dibuka',
                'laporan_foto'      => null,
                'tingkat_kerusakan' => 'rendah',
                'tingkat_urgensi'   => 'rendah',
                'dampak_kerusakan'  => 'kecil',
                'status_laporan'    => 'diproses',
                'tanggal_diproses'  => Carbon::now()->subDays(2),
                'tanggal_selesai'   => null,
                'bobot'             => 0.29,
                'created_at'        => Carbon::now()->subDays(3),
                'updated_at'        => Carbon::now()->subDays(2),
            ],
            [
                'user_id'           => 3,
                'role'              => 'mhs',
                'gedung_id'         => 1,
                'lantai_id'         => 5,
                'ruang_id'          => 6,
                'sarana_id'         => 36,
                'teknisi_id'        => 1,
                'laporan_judul'     => 'Whiteboard rusak tidak bisa dihapus',
                'laporan_foto'      => null,
                'tingkat_kerusakan' => 'sedang',
                'tingkat_urgensi'   => 'rendah',
                'dampak_kerusakan'  => 'kecil',
                'status_laporan'    => 'pending',
                'tanggal_diproses'  => null,
                'tanggal_selesai'   => null,
                'bobot'             => 0.32,
                'created_at'        => Carbon::now()->subHours(3),
                'updated_at'        => Carbon::now()->subHours(3),
            ],
            [
                'user_id'           => 5,
                'role'              => 'tendik',
                'gedung_id'         => 1,
                'lantai_id'         => 8,
                'ruang_id'          => 67,
                'sarana_id'         => 37,
                'teknisi_id'        => 1,
                'laporan_judul'     => 'Kipas angin tidak berputar',
                'laporan_foto'      => 'laporan_files/kipas_rusak.jpg',
                'tingkat_kerusakan' => 'rendah',
                'tingkat_urgensi'   => 'rendah',
                'dampak_kerusakan'  => 'kecil',
                'status_laporan'    => 'pending',
                'tanggal_diproses'  => null,
                'tanggal_selesai'   => null,
                'bobot'             => 0.25,
                'created_at'        => Carbon::now()->subHours(2),
                'updated_at'        => Carbon::now()->subHours(2),
            ],
            [
                'user_id'           => 4,
                'role'              => 'dosen',
                'gedung_id'         => 1,
                'lantai_id'         => 5,
                'ruang_id'          => 2,
                'sarana_id'         => 38,
                'teknisi_id'        => 1,
                'laporan_judul'     => 'Meja dosen goyang',
                'laporan_foto'      => null,
                'tingkat_kerusakan' => 'rendah',
                'tingkat_urgensi'   => 'sedang',
                'dampak_kerusakan'  => 'kecil',
                'status_laporan'    => 'ditolak',
                'tanggal_diproses'  => null,
                'tanggal_selesai'   => null,
                'bobot'             => 0.35,
                'created_at'        => Carbon::now()->subHour(),
                'updated_at'        => Carbon::now()->subHour(),
            ],
        ]);
    }
}
